N_IND = 0
C_IND = 1
H_IND = 2
W_IND = 3
F_K_IND = 0
F_C_IND = 1
F_R_IND = 2
F_S_IND = 3
IMG_IND = 0
FILT_IND = 1

RNN_IN_SEQ_LEN_IND = 0
RNN_IN_BS_IND = 1
RNN_IN_SZ_IND = 2
RNN_OUT_SEQ_LEN_IND = 0
RNN_OUT_NUM_DIR_IND = 1
RNN_OUT_BS_IND = 2
RNN_OUT_HIDDEN_SZ_IND = 3
RNN_IN_WT_NUM_DIR_IND = 0
RNN_IN_WT_HIDDEN_SZ_IND = 1
RNN_IN_WT_SZ_IND = 2
RNN_RC_WT_NUM_DIR_IND = 0
RNN_RC_WT_HIDDEN_SZ_IND_1 = 1
RNN_RC_WT_HIDDEN_SZ_IND_2 = 2
RNN_IN_SEQ_IND = 0
RNN_IN_WT_IND = 1
RNN_RC_WT_IND = 2

GEMM_M_IND = 0
GEMM_N_IND = 1
GEMM_K_IND = 2

INSTR_M_IND = 0
INSTR_N_IND = 1
INSTR_K_IND = 2
INSTR_NUM_BLOCKS_IND = 3

ATTN_BS_IND = 0
ATTN_HIDDEN_SZ_IND = 2
ATTN_SEQ_LEN_IND = 3

EMB_BS_IND = 0
EMB_DIM_IND = 1
EMB_NUM_LUT_ROWS_IND = 0
EMB_NUM_LUT_INDICES_IND = 1

STREAM_L2_HIT_RATE = 0
HIGH_L2_HIT_RATE = 1
STREAM_L3_HIT_RATE = 0
HIGH_L3_HIT_RATE = 1

ALLREDUCE_NUM_CU_FACTOR = 2
ALLREDUCE_ITER_LIMIT = 4

TPU_INF_PARTITION_SCHEMES = ['aggresive', 'conservative']

INVALID_LARGE_VAL = 1 << 63

# TPU/ML Chiplet constants
MODERATE_LV1_SRAM_THRESH = 4
MODERATE_LV2_SRAM_THRESH = 8
SLICE_SPLIT = 2  # XPEs within a slice are split into 'SLICE_SPLIT' ways to reduce R2R latency
PIPELINE_ACTIVATION_BLOCKS = 16  # Assumption: 16 activation blocks to cover internal XPE calculation latency;
                                 # This also dictates the maximum SRAM space dedicated for activations


#================== CALIBRATION CONSTANTS ================== # (TTrace/assembly eyeball measurements)
WI_PER_WAVE = 64
SIMD_PER_CU = 4
CC_PER_ALU_INSTR = 4

CALIBRATING = False
CALIBRATION_CLOCK = 1401  # MHz

#--- BATCHNORM
DEGRADE_FACTOR = 0.15
BNORM_UNROLL_FACTOR = 2
BEST_CASE_UNROLL_FACTOR = 32
ADDR_CALC_OPS_NUM = 4
REDUCE_MEAN_VAR_OPS_NUM = 12#3
APPLY_BNORM_OPS_NUM = 6#4
REDUCE_DS_DB_OPS_NUM = 30
CALC_DX_OUT_OPS_NUM = 12
DPP_CC_PER_WAVE = 500
LDS_CC_PER_WAVE = 64 * BNORM_UNROLL_FACTOR  # cc per BNORM_UNROLL_FACTOR iterations
MAD_SQRT_ETC_CC = 1500
# Variant 0,1 related
RAMPDOWN_CC = 350
INST_FETCH_BUBBLE_VAR0_VAR1_BWD = 4000
DPP_LDS_CC_VAR0_VAR1 = 2000
DPP_LDS_CC_BWD = 3500
MAD_SQRT_ETC_CC_VAR0_VAR1 = 400
DEFAULT_WG_SIZE = 1024
SPILL_THRES_FWD = 32768  # 128*16*16 a.k.a NHW: determined by looking at assembly
SPILL_THRES_BWD = 16384  # 64*16*16 or 16*32*32 a.k.a NHW: determined by looking at assembly
PIPELINE_PUSHBACK_FACTOR = 0.5  # [0:1] the closer to 1 the more cycles pipeline pushback costs
