# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'guiMainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1388, 799)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(3, 3, 3, 3)
        self.horizontalLayout.setSpacing(3)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setOpaqueResize(True)
        self.splitter.setHandleWidth(3)
        self.splitter.setChildrenCollapsible(True)
        self.splitter.setObjectName("splitter")
        self.frameLeft = QtWidgets.QFrame(self.splitter)
        self.frameLeft.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frameLeft.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameLeft.setObjectName("frameLeft")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frameLeft)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setSpacing(3)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.frameDnnConf = QtWidgets.QFrame(self.frameLeft)
        self.frameDnnConf.setFrameShape(QtWidgets.QFrame.Panel)
        self.frameDnnConf.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameDnnConf.setObjectName("frameDnnConf")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frameDnnConf)
        self.verticalLayout_3.setContentsMargins(3, 3, 3, 3)
        self.verticalLayout_3.setSpacing(3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frameTitle_1 = QtWidgets.QFrame(self.frameDnnConf)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameTitle_1.sizePolicy().hasHeightForWidth())
        self.frameTitle_1.setSizePolicy(sizePolicy)
        self.frameTitle_1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameTitle_1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameTitle_1.setObjectName("frameTitle_1")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frameTitle_1)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.line_1 = QtWidgets.QFrame(self.frameTitle_1)
        self.line_1.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_1.setObjectName("line_1")
        self.horizontalLayout_5.addWidget(self.line_1)
        self.lblDnnConf = QtWidgets.QLabel(self.frameTitle_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblDnnConf.sizePolicy().hasHeightForWidth())
        self.lblDnnConf.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.lblDnnConf.setFont(font)
        self.lblDnnConf.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblDnnConf.setObjectName("lblDnnConf")
        self.horizontalLayout_5.addWidget(self.lblDnnConf)
        self.line_4 = QtWidgets.QFrame(self.frameTitle_1)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.horizontalLayout_5.addWidget(self.line_4)
        self.verticalLayout_3.addWidget(self.frameTitle_1)
        self.gBoxSWOpt = QtWidgets.QGroupBox(self.frameDnnConf)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gBoxSWOpt.sizePolicy().hasHeightForWidth())
        self.gBoxSWOpt.setSizePolicy(sizePolicy)
        self.gBoxSWOpt.setAlignment(QtCore.Qt.AlignCenter)
        self.gBoxSWOpt.setObjectName("gBoxSWOpt")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.gBoxSWOpt)
        self.verticalLayout_4.setContentsMargins(3, 3, 3, 5)
        self.verticalLayout_4.setSpacing(4)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frameBttns = QtWidgets.QFrame(self.gBoxSWOpt)
        self.frameBttns.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frameBttns.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameBttns.setLineWidth(0)
        self.frameBttns.setObjectName("frameBttns")
        self.gridLayout = QtWidgets.QGridLayout(self.frameBttns)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setHorizontalSpacing(3)
        self.gridLayout.setObjectName("gridLayout")
        self.frame_7 = QtWidgets.QFrame(self.frameBttns)
        self.frame_7.setMaximumSize(QtCore.QSize(16777215, 52))
        self.frame_7.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout_17.setContentsMargins(1, 1, 2, 2)
        self.horizontalLayout_17.setSpacing(3)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.cBoxModels = QtWidgets.QComboBox(self.frame_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cBoxModels.sizePolicy().hasHeightForWidth())
        self.cBoxModels.setSizePolicy(sizePolicy)
        self.cBoxModels.setMaxVisibleItems(35)
        self.cBoxModels.setFrame(True)
        self.cBoxModels.setObjectName("cBoxModels")
        self.cBoxModels.addItem("")
        self.horizontalLayout_17.addWidget(self.cBoxModels)
        self.gridLayout.addWidget(self.frame_7, 0, 1, 1, 1)
        self.frame_5 = QtWidgets.QFrame(self.frameBttns)
        self.frame_5.setMinimumSize(QtCore.QSize(52, 0))
        self.frame_5.setMaximumSize(QtCore.QSize(52, 16777215))
        self.frame_5.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_14.setContentsMargins(3, 1, 2, 1)
        self.horizontalLayout_14.setSpacing(3)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.chBoxRL = QtWidgets.QCheckBox(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chBoxRL.sizePolicy().hasHeightForWidth())
        self.chBoxRL.setSizePolicy(sizePolicy)
        self.chBoxRL.setText("")
        self.chBoxRL.setObjectName("chBoxRL")
        self.horizontalLayout_14.addWidget(self.chBoxRL)
        self.btnRL = QtWidgets.QToolButton(self.frame_5)
        self.btnRL.setMinimumSize(QtCore.QSize(0, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.btnRL.setFont(font)
        self.btnRL.setAutoRaise(True)
        self.btnRL.setObjectName("btnRL")
        self.horizontalLayout_14.addWidget(self.btnRL)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem)
        self.gridLayout.addWidget(self.frame_5, 0, 4, 1, 1)
        self.frame_6 = QtWidgets.QFrame(self.frameBttns)
        self.frame_6.setMinimumSize(QtCore.QSize(94, 0))
        self.frame_6.setMaximumSize(QtCore.QSize(94, 16777215))
        self.frame_6.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_15.setContentsMargins(3, 1, 2, 1)
        self.horizontalLayout_15.setSpacing(3)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.chBoxMGPU = QtWidgets.QCheckBox(self.frame_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chBoxMGPU.sizePolicy().hasHeightForWidth())
        self.chBoxMGPU.setSizePolicy(sizePolicy)
        self.chBoxMGPU.setText("")
        self.chBoxMGPU.setObjectName("chBoxMGPU")
        self.horizontalLayout_15.addWidget(self.chBoxMGPU)
        self.btnMGPU = QtWidgets.QToolButton(self.frame_6)
        self.btnMGPU.setMinimumSize(QtCore.QSize(0, 21))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.btnMGPU.setFont(font)
        self.btnMGPU.setAutoRaise(True)
        self.btnMGPU.setObjectName("btnMGPU")
        self.horizontalLayout_15.addWidget(self.btnMGPU)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem1)
        self.gridLayout.addWidget(self.frame_6, 0, 3, 1, 1)
        self.frame_4 = QtWidgets.QFrame(self.frameBttns)
        self.frame_4.setMinimumSize(QtCore.QSize(64, 0))
        self.frame_4.setMaximumSize(QtCore.QSize(64, 16777215))
        self.frame_4.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_13.setContentsMargins(1, 1, 2, 1)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.btnGeneral = QtWidgets.QToolButton(self.frame_4)
        self.btnGeneral.setMinimumSize(QtCore.QSize(0, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btnGeneral.setFont(font)
        self.btnGeneral.setCheckable(False)
        self.btnGeneral.setAutoRaise(True)
        self.btnGeneral.setObjectName("btnGeneral")
        self.horizontalLayout_13.addWidget(self.btnGeneral)
        self.gridLayout.addWidget(self.frame_4, 0, 2, 1, 1)
        self.frame_3 = QtWidgets.QFrame(self.frameBttns)
        self.frame_3.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_18.setContentsMargins(3, 1, 2, 1)
        self.horizontalLayout_18.setSpacing(3)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem2)
        self.gridLayout.addWidget(self.frame_3, 0, 5, 1, 1)
        self.verticalLayout_4.addWidget(self.frameBttns)
        self.frameSwOpt = QtWidgets.QFrame(self.gBoxSWOpt)
        self.frameSwOpt.setFrameShape(QtWidgets.QFrame.Panel)
        self.frameSwOpt.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frameSwOpt.setLineWidth(1)
        self.frameSwOpt.setObjectName("frameSwOpt")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frameSwOpt)
        self.verticalLayout_2.setContentsMargins(6, 0, 6, 0)
        self.verticalLayout_2.setSpacing(3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.wgtExtOpt = QtWidgets.QStackedWidget(self.frameSwOpt)
        self.wgtExtOpt.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.wgtExtOpt.setFrameShadow(QtWidgets.QFrame.Plain)
        self.wgtExtOpt.setLineWidth(0)
        self.wgtExtOpt.setObjectName("wgtExtOpt")
        self.pageGeneral = QtWidgets.QWidget()
        self.pageGeneral.setObjectName("pageGeneral")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.pageGeneral)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.chBoxTraining = QtWidgets.QCheckBox(self.pageGeneral)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chBoxTraining.sizePolicy().hasHeightForWidth())
        self.chBoxTraining.setSizePolicy(sizePolicy)
        self.chBoxTraining.setChecked(True)
        self.chBoxTraining.setObjectName("chBoxTraining")
        self.horizontalLayout_3.addWidget(self.chBoxTraining)
        self.chBoxFusion = QtWidgets.QCheckBox(self.pageGeneral)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chBoxFusion.sizePolicy().hasHeightForWidth())
        self.chBoxFusion.setSizePolicy(sizePolicy)
        self.chBoxFusion.setObjectName("chBoxFusion")
        self.horizontalLayout_3.addWidget(self.chBoxFusion)
        self.label_2 = QtWidgets.QLabel(self.pageGeneral)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.cBoxDataFormat = QtWidgets.QComboBox(self.pageGeneral)
        self.cBoxDataFormat.setMaximumSize(QtCore.QSize(16777215, 17))
        self.cBoxDataFormat.setObjectName("cBoxDataFormat")
        self.cBoxDataFormat.addItem("")
        self.cBoxDataFormat.addItem("")
        self.cBoxDataFormat.addItem("")
        self.cBoxDataFormat.addItem("")
        self.cBoxDataFormat.addItem("")
        self.horizontalLayout_3.addWidget(self.cBoxDataFormat)
        self.label = QtWidgets.QLabel(self.pageGeneral)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.txtBatchSize = QtWidgets.QLineEdit(self.pageGeneral)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtBatchSize.sizePolicy().hasHeightForWidth())
        self.txtBatchSize.setSizePolicy(sizePolicy)
        self.txtBatchSize.setMaximumSize(QtCore.QSize(30, 15))
        self.txtBatchSize.setAlignment(QtCore.Qt.AlignCenter)
        self.txtBatchSize.setObjectName("txtBatchSize")
        self.horizontalLayout_3.addWidget(self.txtBatchSize)
        self.chBoxOptimizeGraph = QtWidgets.QCheckBox(self.pageGeneral)
        self.chBoxOptimizeGraph.setChecked(True)
        self.chBoxOptimizeGraph.setObjectName("chBoxOptimizeGraph")
        self.horizontalLayout_3.addWidget(self.chBoxOptimizeGraph)
        self.chBoxCalibrated = QtWidgets.QCheckBox(self.pageGeneral)
        self.chBoxCalibrated.setObjectName("chBoxCalibrated")
        self.horizontalLayout_3.addWidget(self.chBoxCalibrated)
        self.chBoxABinLDS = QtWidgets.QCheckBox(self.pageGeneral)
        self.chBoxABinLDS.setObjectName("chBoxABinLDS")
        self.horizontalLayout_3.addWidget(self.chBoxABinLDS)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.wgtExtOpt.addWidget(self.pageGeneral)
        self.pageRL = QtWidgets.QWidget()
        self.pageRL.setObjectName("pageRL")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.pageRL)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setSpacing(6)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_6 = QtWidgets.QLabel(self.pageRL)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_11.addWidget(self.label_6)
        self.txtTmax = QtWidgets.QLineEdit(self.pageRL)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtTmax.sizePolicy().hasHeightForWidth())
        self.txtTmax.setSizePolicy(sizePolicy)
        self.txtTmax.setMaximumSize(QtCore.QSize(30, 15))
        self.txtTmax.setAlignment(QtCore.Qt.AlignCenter)
        self.txtTmax.setObjectName("txtTmax")
        self.horizontalLayout_11.addWidget(self.txtTmax)
        self.line_12 = QtWidgets.QFrame(self.pageRL)
        self.line_12.setMaximumSize(QtCore.QSize(16777215, 10))
        self.line_12.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_12.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_12.setObjectName("line_12")
        self.horizontalLayout_11.addWidget(self.line_12)
        self.label_5 = QtWidgets.QLabel(self.pageRL)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_11.addWidget(self.label_5)
        self.txtCpuThreads = QtWidgets.QLineEdit(self.pageRL)
        self.txtCpuThreads.setMaximumSize(QtCore.QSize(30, 15))
        self.txtCpuThreads.setAlignment(QtCore.Qt.AlignCenter)
        self.txtCpuThreads.setObjectName("txtCpuThreads")
        self.horizontalLayout_11.addWidget(self.txtCpuThreads)
        spacerItem4 = QtWidgets.QSpacerItem(305, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem4)
        self.wgtExtOpt.addWidget(self.pageRL)
        self.pageMGPU = QtWidgets.QWidget()
        self.pageMGPU.setObjectName("pageMGPU")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.pageMGPU)
        self.horizontalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_16.setSpacing(6)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_4 = QtWidgets.QLabel(self.pageMGPU)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_16.addWidget(self.label_4)
        self.txtGPUCount = QtWidgets.QLineEdit(self.pageMGPU)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtGPUCount.sizePolicy().hasHeightForWidth())
        self.txtGPUCount.setSizePolicy(sizePolicy)
        self.txtGPUCount.setMaximumSize(QtCore.QSize(30, 15))
        self.txtGPUCount.setAlignment(QtCore.Qt.AlignCenter)
        self.txtGPUCount.setObjectName("txtGPUCount")
        self.horizontalLayout_16.addWidget(self.txtGPUCount)
        self.line_8 = QtWidgets.QFrame(self.pageMGPU)
        self.line_8.setMaximumSize(QtCore.QSize(16777215, 10))
        self.line_8.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.horizontalLayout_16.addWidget(self.line_8)
        self.label_7 = QtWidgets.QLabel(self.pageMGPU)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_16.addWidget(self.label_7)
        self.txtXGMILinksPerGPU = QtWidgets.QLineEdit(self.pageMGPU)
        self.txtXGMILinksPerGPU.setMaximumSize(QtCore.QSize(30, 15))
        self.txtXGMILinksPerGPU.setAlignment(QtCore.Qt.AlignCenter)
        self.txtXGMILinksPerGPU.setObjectName("txtXGMILinksPerGPU")
        self.horizontalLayout_16.addWidget(self.txtXGMILinksPerGPU)
        self.line_16 = QtWidgets.QFrame(self.pageMGPU)
        self.line_16.setMaximumSize(QtCore.QSize(16777215, 10))
        self.line_16.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_16.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_16.setObjectName("line_16")
        self.horizontalLayout_16.addWidget(self.line_16)
        self.label_11 = QtWidgets.QLabel(self.pageMGPU)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_16.addWidget(self.label_11)
        self.txtXGMI_BW = QtWidgets.QLineEdit(self.pageMGPU)
        self.txtXGMI_BW.setMaximumSize(QtCore.QSize(30, 15))
        self.txtXGMI_BW.setAlignment(QtCore.Qt.AlignCenter)
        self.txtXGMI_BW.setObjectName("txtXGMI_BW")
        self.horizontalLayout_16.addWidget(self.txtXGMI_BW)
        self.line_17 = QtWidgets.QFrame(self.pageMGPU)
        self.line_17.setMaximumSize(QtCore.QSize(16777215, 10))
        self.line_17.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_17.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_17.setObjectName("line_17")
        self.horizontalLayout_16.addWidget(self.line_17)
        self.label_12 = QtWidgets.QLabel(self.pageMGPU)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_16.addWidget(self.label_12)
        self.txtXGMI_BWEfficiency = QtWidgets.QLineEdit(self.pageMGPU)
        self.txtXGMI_BWEfficiency.setMaximumSize(QtCore.QSize(30, 15))
        self.txtXGMI_BWEfficiency.setAlignment(QtCore.Qt.AlignCenter)
        self.txtXGMI_BWEfficiency.setObjectName("txtXGMI_BWEfficiency")
        self.horizontalLayout_16.addWidget(self.txtXGMI_BWEfficiency)
        self.line_13 = QtWidgets.QFrame(self.pageMGPU)
        self.line_13.setMaximumSize(QtCore.QSize(16777215, 10))
        self.line_13.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_13.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_13.setObjectName("line_13")
        self.horizontalLayout_16.addWidget(self.line_13)
        self.label_13 = QtWidgets.QLabel(self.pageMGPU)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_16.addWidget(self.label_13)
        self.txtNumGradientBits = QtWidgets.QLineEdit(self.pageMGPU)
        self.txtNumGradientBits.setMaximumSize(QtCore.QSize(30, 15))
        self.txtNumGradientBits.setAlignment(QtCore.Qt.AlignCenter)
        self.txtNumGradientBits.setObjectName("txtNumGradientBits")
        self.horizontalLayout_16.addWidget(self.txtNumGradientBits)
        self.line_19 = QtWidgets.QFrame(self.pageMGPU)
        self.line_19.setMaximumSize(QtCore.QSize(16777215, 10))
        self.line_19.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_19.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_19.setObjectName("line_19")
        self.horizontalLayout_16.addWidget(self.line_19)
        self.label_10 = QtWidgets.QLabel(self.pageMGPU)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_16.addWidget(self.label_10)
        self.txtStartupLatency = QtWidgets.QLineEdit(self.pageMGPU)
        self.txtStartupLatency.setMaximumSize(QtCore.QSize(30, 15))
        self.txtStartupLatency.setAlignment(QtCore.Qt.AlignCenter)
        self.txtStartupLatency.setObjectName("txtStartupLatency")
        self.horizontalLayout_16.addWidget(self.txtStartupLatency)
        self.line_14 = QtWidgets.QFrame(self.pageMGPU)
        self.line_14.setMaximumSize(QtCore.QSize(16777215, 10))
        self.line_14.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_14.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_14.setObjectName("line_14")
        self.horizontalLayout_16.addWidget(self.line_14)
        self.chBoxWeakScaling = QtWidgets.QCheckBox(self.pageMGPU)
        self.chBoxWeakScaling.setChecked(True)
        self.chBoxWeakScaling.setObjectName("chBoxWeakScaling")
        self.horizontalLayout_16.addWidget(self.chBoxWeakScaling)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem5)
        self.wgtExtOpt.addWidget(self.pageMGPU)
        self.verticalLayout_2.addWidget(self.wgtExtOpt)
        self.wgtExtOpt_row2 = QtWidgets.QStackedWidget(self.frameSwOpt)
        self.wgtExtOpt_row2.setObjectName("wgtExtOpt_row2")
        self.pageGeneral_2 = QtWidgets.QWidget()
        self.pageGeneral_2.setObjectName("pageGeneral_2")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout(self.pageGeneral_2)
        self.horizontalLayout_19.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.chBoxDisableL2Opti = QtWidgets.QCheckBox(self.pageGeneral_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chBoxDisableL2Opti.sizePolicy().hasHeightForWidth())
        self.chBoxDisableL2Opti.setSizePolicy(sizePolicy)
        self.chBoxDisableL2Opti.setObjectName("chBoxDisableL2Opti")
        self.horizontalLayout_19.addWidget(self.chBoxDisableL2Opti)
        self.chBoxDisableTrailKRepart = QtWidgets.QCheckBox(self.pageGeneral_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chBoxDisableTrailKRepart.sizePolicy().hasHeightForWidth())
        self.chBoxDisableTrailKRepart.setSizePolicy(sizePolicy)
        self.chBoxDisableTrailKRepart.setObjectName("chBoxDisableTrailKRepart")
        self.horizontalLayout_19.addWidget(self.chBoxDisableTrailKRepart)
        self.chBoxDisableMainKPart = QtWidgets.QCheckBox(self.pageGeneral_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chBoxDisableMainKPart.sizePolicy().hasHeightForWidth())
        self.chBoxDisableMainKPart.setSizePolicy(sizePolicy)
        self.chBoxDisableMainKPart.setObjectName("chBoxDisableMainKPart")
        self.horizontalLayout_19.addWidget(self.chBoxDisableMainKPart)
        self.chBoxDisableTrailOpti = QtWidgets.QCheckBox(self.pageGeneral_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.chBoxDisableTrailOpti.sizePolicy().hasHeightForWidth())
        self.chBoxDisableTrailOpti.setSizePolicy(sizePolicy)
        self.chBoxDisableTrailOpti.setObjectName("chBoxDisableTrailOpti")
        self.horizontalLayout_19.addWidget(self.chBoxDisableTrailOpti)
        self.label_18 = QtWidgets.QLabel(self.pageGeneral_2)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_19.addWidget(self.label_18)
        self.txtPerfThreshold = QtWidgets.QLineEdit(self.pageGeneral_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtPerfThreshold.sizePolicy().hasHeightForWidth())
        self.txtPerfThreshold.setSizePolicy(sizePolicy)
        self.txtPerfThreshold.setMaximumSize(QtCore.QSize(30, 15))
        self.txtPerfThreshold.setAlignment(QtCore.Qt.AlignCenter)
        self.txtPerfThreshold.setObjectName("txtPerfThreshold")
        self.horizontalLayout_19.addWidget(self.txtPerfThreshold)
        self.chBoxTileGranularity = QtWidgets.QCheckBox(self.pageGeneral_2)
        self.chBoxTileGranularity.setObjectName("chBoxTileGranularity")
        self.horizontalLayout_19.addWidget(self.chBoxTileGranularity)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem6)
        self.wgtExtOpt_row2.addWidget(self.pageGeneral_2)
        self.pageRL_2 = QtWidgets.QWidget()
        self.pageRL_2.setObjectName("pageRL_2")
        self.wgtExtOpt_row2.addWidget(self.pageRL_2)
        self.pageMGPU_2 = QtWidgets.QWidget()
        self.pageMGPU_2.setObjectName("pageMGPU_2")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.pageMGPU_2)
        self.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_12.setSpacing(6)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_8 = QtWidgets.QLabel(self.pageMGPU_2)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_12.addWidget(self.label_8)
        self.cBoxAlgorithm = QtWidgets.QComboBox(self.pageMGPU_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cBoxAlgorithm.sizePolicy().hasHeightForWidth())
        self.cBoxAlgorithm.setSizePolicy(sizePolicy)
        self.cBoxAlgorithm.setMaximumSize(QtCore.QSize(16777215, 17))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.cBoxAlgorithm.setFont(font)
        self.cBoxAlgorithm.setObjectName("cBoxAlgorithm")
        self.cBoxAlgorithm.addItem("")
        self.cBoxAlgorithm.addItem("")
        self.cBoxAlgorithm.addItem("")
        self.cBoxAlgorithm.addItem("")
        self.horizontalLayout_12.addWidget(self.cBoxAlgorithm)
        self.line_11 = QtWidgets.QFrame(self.pageMGPU_2)
        self.line_11.setMaximumSize(QtCore.QSize(16777215, 10))
        self.line_11.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.horizontalLayout_12.addWidget(self.line_11)
        self.label_9 = QtWidgets.QLabel(self.pageMGPU_2)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_12.addWidget(self.label_9)
        self.cBoxTopology = QtWidgets.QComboBox(self.pageMGPU_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cBoxTopology.sizePolicy().hasHeightForWidth())
        self.cBoxTopology.setSizePolicy(sizePolicy)
        self.cBoxTopology.setMaximumSize(QtCore.QSize(16777215, 17))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.cBoxTopology.setFont(font)
        self.cBoxTopology.setObjectName("cBoxTopology")
        self.cBoxTopology.addItem("")
        self.cBoxTopology.addItem("")
        self.cBoxTopology.addItem("")
        self.cBoxTopology.addItem("")
        self.cBoxTopology.addItem("")
        self.horizontalLayout_12.addWidget(self.cBoxTopology)
        self.line_18 = QtWidgets.QFrame(self.pageMGPU_2)
        self.line_18.setMaximumSize(QtCore.QSize(16777215, 10))
        self.line_18.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_18.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_18.setObjectName("line_18")
        self.horizontalLayout_12.addWidget(self.line_18)
        self.label_14 = QtWidgets.QLabel(self.pageMGPU_2)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_12.addWidget(self.label_14)
        self.txtMultiNode = QtWidgets.QLineEdit(self.pageMGPU_2)
        self.txtMultiNode.setMinimumSize(QtCore.QSize(0, 0))
        self.txtMultiNode.setMaximumSize(QtCore.QSize(30, 15))
        self.txtMultiNode.setAlignment(QtCore.Qt.AlignCenter)
        self.txtMultiNode.setObjectName("txtMultiNode")
        self.horizontalLayout_12.addWidget(self.txtMultiNode)
        self.line_20 = QtWidgets.QFrame(self.pageMGPU_2)
        self.line_20.setMaximumSize(QtCore.QSize(16777215, 10))
        self.line_20.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_20.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_20.setObjectName("line_20")
        self.horizontalLayout_12.addWidget(self.line_20)
        self.label_15 = QtWidgets.QLabel(self.pageMGPU_2)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_12.addWidget(self.label_15)
        self.txtMultiNodeBW = QtWidgets.QLineEdit(self.pageMGPU_2)
        self.txtMultiNodeBW.setMaximumSize(QtCore.QSize(30, 15))
        self.txtMultiNodeBW.setAlignment(QtCore.Qt.AlignCenter)
        self.txtMultiNodeBW.setObjectName("txtMultiNodeBW")
        self.horizontalLayout_12.addWidget(self.txtMultiNodeBW)
        self.line_21 = QtWidgets.QFrame(self.pageMGPU_2)
        self.line_21.setMaximumSize(QtCore.QSize(16777215, 10))
        self.line_21.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_21.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_21.setObjectName("line_21")
        self.horizontalLayout_12.addWidget(self.line_21)
        self.label_16 = QtWidgets.QLabel(self.pageMGPU_2)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_12.addWidget(self.label_16)
        self.txtMultiNodeLinks = QtWidgets.QLineEdit(self.pageMGPU_2)
        self.txtMultiNodeLinks.setMaximumSize(QtCore.QSize(30, 15))
        self.txtMultiNodeLinks.setAlignment(QtCore.Qt.AlignCenter)
        self.txtMultiNodeLinks.setObjectName("txtMultiNodeLinks")
        self.horizontalLayout_12.addWidget(self.txtMultiNodeLinks)
        self.line_22 = QtWidgets.QFrame(self.pageMGPU_2)
        self.line_22.setMaximumSize(QtCore.QSize(16777215, 10))
        self.line_22.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_22.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_22.setObjectName("line_22")
        self.horizontalLayout_12.addWidget(self.line_22)
        self.label_17 = QtWidgets.QLabel(self.pageMGPU_2)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_12.addWidget(self.label_17)
        self.txtMNStartupLatency = QtWidgets.QLineEdit(self.pageMGPU_2)
        self.txtMNStartupLatency.setMaximumSize(QtCore.QSize(30, 15))
        self.txtMNStartupLatency.setAlignment(QtCore.Qt.AlignCenter)
        self.txtMNStartupLatency.setObjectName("txtMNStartupLatency")
        self.horizontalLayout_12.addWidget(self.txtMNStartupLatency)
        self.line_23 = QtWidgets.QFrame(self.pageMGPU_2)
        self.line_23.setMaximumSize(QtCore.QSize(16777215, 10))
        self.line_23.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_23.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_23.setObjectName("line_23")
        self.horizontalLayout_12.addWidget(self.line_23)
        self.chBoxSDMA_Xfer = QtWidgets.QCheckBox(self.pageMGPU_2)
        self.chBoxSDMA_Xfer.setObjectName("chBoxSDMA_Xfer")
        self.horizontalLayout_12.addWidget(self.chBoxSDMA_Xfer)
        spacerItem7 = QtWidgets.QSpacerItem(412, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem7)
        self.wgtExtOpt_row2.addWidget(self.pageMGPU_2)
        self.verticalLayout_2.addWidget(self.wgtExtOpt_row2)
        self.wgtExtOpt_row3 = QtWidgets.QStackedWidget(self.frameSwOpt)
        self.wgtExtOpt_row3.setObjectName("wgtExtOpt_row3")
        self.pageGeneral_3 = QtWidgets.QWidget()
        self.pageGeneral_3.setObjectName("pageGeneral_3")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout(self.pageGeneral_3)
        self.horizontalLayout_20.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.chBoxUserDefMT = QtWidgets.QCheckBox(self.pageGeneral_3)
        self.chBoxUserDefMT.setObjectName("chBoxUserDefMT")
        self.horizontalLayout_20.addWidget(self.chBoxUserDefMT)
        self.label_21 = QtWidgets.QLabel(self.pageGeneral_3)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_20.addWidget(self.label_21)
        self.txtMainMT0 = QtWidgets.QLineEdit(self.pageGeneral_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtMainMT0.sizePolicy().hasHeightForWidth())
        self.txtMainMT0.setSizePolicy(sizePolicy)
        self.txtMainMT0.setMaximumSize(QtCore.QSize(30, 15))
        self.txtMainMT0.setAlignment(QtCore.Qt.AlignCenter)
        self.txtMainMT0.setObjectName("txtMainMT0")
        self.horizontalLayout_20.addWidget(self.txtMainMT0)
        self.label_22 = QtWidgets.QLabel(self.pageGeneral_3)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_20.addWidget(self.label_22)
        self.txtMainMT1 = QtWidgets.QLineEdit(self.pageGeneral_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtMainMT1.sizePolicy().hasHeightForWidth())
        self.txtMainMT1.setSizePolicy(sizePolicy)
        self.txtMainMT1.setMaximumSize(QtCore.QSize(30, 15))
        self.txtMainMT1.setAlignment(QtCore.Qt.AlignCenter)
        self.txtMainMT1.setObjectName("txtMainMT1")
        self.horizontalLayout_20.addWidget(self.txtMainMT1)
        self.chBoxNoTrail = QtWidgets.QCheckBox(self.pageGeneral_3)
        self.chBoxNoTrail.setObjectName("chBoxNoTrail")
        self.horizontalLayout_20.addWidget(self.chBoxNoTrail)
        self.label_23 = QtWidgets.QLabel(self.pageGeneral_3)
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_20.addWidget(self.label_23)
        self.txtTrailMT0 = QtWidgets.QLineEdit(self.pageGeneral_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtTrailMT0.sizePolicy().hasHeightForWidth())
        self.txtTrailMT0.setSizePolicy(sizePolicy)
        self.txtTrailMT0.setMaximumSize(QtCore.QSize(30, 15))
        self.txtTrailMT0.setAlignment(QtCore.Qt.AlignCenter)
        self.txtTrailMT0.setObjectName("txtTrailMT0")
        self.horizontalLayout_20.addWidget(self.txtTrailMT0)
        self.label_24 = QtWidgets.QLabel(self.pageGeneral_3)
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_20.addWidget(self.label_24)
        self.txtTrailMT1 = QtWidgets.QLineEdit(self.pageGeneral_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtTrailMT1.sizePolicy().hasHeightForWidth())
        self.txtTrailMT1.setSizePolicy(sizePolicy)
        self.txtTrailMT1.setMaximumSize(QtCore.QSize(30, 15))
        self.txtTrailMT1.setAlignment(QtCore.Qt.AlignCenter)
        self.txtTrailMT1.setObjectName("txtTrailMT1")
        self.horizontalLayout_20.addWidget(self.txtTrailMT1)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem8)
        self.wgtExtOpt_row3.addWidget(self.pageGeneral_3)
        self.pageRL_3 = QtWidgets.QWidget()
        self.pageRL_3.setObjectName("pageRL_3")
        self.wgtExtOpt_row3.addWidget(self.pageRL_3)
        self.pageMGPU_3 = QtWidgets.QWidget()
        self.pageMGPU_3.setObjectName("pageMGPU_3")
        self.wgtExtOpt_row3.addWidget(self.pageMGPU_3)
        self.verticalLayout_2.addWidget(self.wgtExtOpt_row3)
        self.verticalLayout_4.addWidget(self.frameSwOpt)
        self.verticalLayout_3.addWidget(self.gBoxSWOpt)
        self.gBoxPreviewModel = QtWidgets.QGroupBox(self.frameDnnConf)
        self.gBoxPreviewModel.setAlignment(QtCore.Qt.AlignCenter)
        self.gBoxPreviewModel.setFlat(False)
        self.gBoxPreviewModel.setCheckable(True)
        self.gBoxPreviewModel.setObjectName("gBoxPreviewModel")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.gBoxPreviewModel)
        self.verticalLayout_8.setContentsMargins(3, 0, 3, 0)
        self.verticalLayout_8.setSpacing(3)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.verticalLayout_3.addWidget(self.gBoxPreviewModel)
        self.verticalLayout_9.addWidget(self.frameDnnConf)
        self.frameRight = QtWidgets.QFrame(self.splitter)
        self.frameRight.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frameRight.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameRight.setObjectName("frameRight")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frameRight)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(3)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.frameHwConf = QtWidgets.QFrame(self.frameRight)
        self.frameHwConf.setFrameShape(QtWidgets.QFrame.Panel)
        self.frameHwConf.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameHwConf.setObjectName("frameHwConf")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frameHwConf)
        self.verticalLayout.setContentsMargins(3, 3, 3, 3)
        self.verticalLayout.setSpacing(3)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frameTitle = QtWidgets.QFrame(self.frameHwConf)
        self.frameTitle.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameTitle.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameTitle.setObjectName("frameTitle")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frameTitle)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.line = QtWidgets.QFrame(self.frameTitle)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setObjectName("line")
        self.horizontalLayout_4.addWidget(self.line)
        self.lblHwConf = QtWidgets.QLabel(self.frameTitle)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblHwConf.sizePolicy().hasHeightForWidth())
        self.lblHwConf.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.lblHwConf.setFont(font)
        self.lblHwConf.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lblHwConf.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblHwConf.setObjectName("lblHwConf")
        self.horizontalLayout_4.addWidget(self.lblHwConf)
        self.line_3 = QtWidgets.QFrame(self.frameTitle)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.horizontalLayout_4.addWidget(self.line_3)
        self.verticalLayout.addWidget(self.frameTitle)
        self.gBoxBaseConf = QtWidgets.QGroupBox(self.frameHwConf)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gBoxBaseConf.sizePolicy().hasHeightForWidth())
        self.gBoxBaseConf.setSizePolicy(sizePolicy)
        self.gBoxBaseConf.setAlignment(QtCore.Qt.AlignCenter)
        self.gBoxBaseConf.setFlat(False)
        self.gBoxBaseConf.setCheckable(False)
        self.gBoxBaseConf.setObjectName("gBoxBaseConf")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.gBoxBaseConf)
        self.verticalLayout_7.setContentsMargins(3, 3, 3, 4)
        self.verticalLayout_7.setSpacing(3)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.frameBaseConfBtn = QtWidgets.QFrame(self.gBoxBaseConf)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameBaseConfBtn.sizePolicy().hasHeightForWidth())
        self.frameBaseConfBtn.setSizePolicy(sizePolicy)
        self.frameBaseConfBtn.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frameBaseConfBtn.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameBaseConfBtn.setObjectName("frameBaseConfBtn")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frameBaseConfBtn)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.cBoxConfs = QtWidgets.QComboBox(self.frameBaseConfBtn)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cBoxConfs.sizePolicy().hasHeightForWidth())
        self.cBoxConfs.setSizePolicy(sizePolicy)
        self.cBoxConfs.setObjectName("cBoxConfs")
        self.cBoxConfs.addItem("")
        self.horizontalLayout_2.addWidget(self.cBoxConfs)
        self.btnNewConf = QtWidgets.QToolButton(self.frameBaseConfBtn)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnNewConf.sizePolicy().hasHeightForWidth())
        self.btnNewConf.setSizePolicy(sizePolicy)
        self.btnNewConf.setObjectName("btnNewConf")
        self.horizontalLayout_2.addWidget(self.btnNewConf)
        self.btnSaveConf = QtWidgets.QToolButton(self.frameBaseConfBtn)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnSaveConf.sizePolicy().hasHeightForWidth())
        self.btnSaveConf.setSizePolicy(sizePolicy)
        self.btnSaveConf.setObjectName("btnSaveConf")
        self.horizontalLayout_2.addWidget(self.btnSaveConf)
        self.btnSaveAsConf = QtWidgets.QToolButton(self.frameBaseConfBtn)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnSaveAsConf.sizePolicy().hasHeightForWidth())
        self.btnSaveAsConf.setSizePolicy(sizePolicy)
        self.btnSaveAsConf.setObjectName("btnSaveAsConf")
        self.horizontalLayout_2.addWidget(self.btnSaveAsConf)
        self.btnDelConf = QtWidgets.QToolButton(self.frameBaseConfBtn)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnDelConf.sizePolicy().hasHeightForWidth())
        self.btnDelConf.setSizePolicy(sizePolicy)
        self.btnDelConf.setObjectName("btnDelConf")
        self.horizontalLayout_2.addWidget(self.btnDelConf)
        self.verticalLayout_7.addWidget(self.frameBaseConfBtn)
        self.tblBaseConf = QtWidgets.QTableView(self.gBoxBaseConf)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tblBaseConf.sizePolicy().hasHeightForWidth())
        self.tblBaseConf.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.tblBaseConf.setFont(font)
        self.tblBaseConf.setFrameShape(QtWidgets.QFrame.Panel)
        self.tblBaseConf.setEditTriggers(QtWidgets.QAbstractItemView.DoubleClicked|QtWidgets.QAbstractItemView.EditKeyPressed)
        self.tblBaseConf.setAlternatingRowColors(True)
        self.tblBaseConf.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tblBaseConf.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.tblBaseConf.setObjectName("tblBaseConf")
        self.tblBaseConf.verticalHeader().setVisible(False)
        self.tblBaseConf.verticalHeader().setDefaultSectionSize(24)
        self.tblBaseConf.verticalHeader().setMinimumSectionSize(18)
        self.verticalLayout_7.addWidget(self.tblBaseConf)
        self.frame = QtWidgets.QFrame(self.gBoxBaseConf)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setSpacing(3)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        spacerItem9 = QtWidgets.QSpacerItem(0, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem9)
        self.btnAddRow = QtWidgets.QToolButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnAddRow.sizePolicy().hasHeightForWidth())
        self.btnAddRow.setSizePolicy(sizePolicy)
        self.btnAddRow.setMaximumSize(QtCore.QSize(20, 20))
        font = QtGui.QFont()
        font.setFamily("Courier")
        font.setPointSize(7)
        self.btnAddRow.setFont(font)
        self.btnAddRow.setAutoRaise(True)
        self.btnAddRow.setObjectName("btnAddRow")
        self.horizontalLayout_8.addWidget(self.btnAddRow)
        self.btnRemRow = QtWidgets.QToolButton(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnRemRow.sizePolicy().hasHeightForWidth())
        self.btnRemRow.setSizePolicy(sizePolicy)
        self.btnRemRow.setMaximumSize(QtCore.QSize(20, 20))
        font = QtGui.QFont()
        font.setFamily("Courier")
        font.setPointSize(7)
        self.btnRemRow.setFont(font)
        self.btnRemRow.setAutoRaise(True)
        self.btnRemRow.setObjectName("btnRemRow")
        self.horizontalLayout_8.addWidget(self.btnRemRow)
        spacerItem10 = QtWidgets.QSpacerItem(0, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem10)
        self.verticalLayout_7.addWidget(self.frame)
        self.tblBaseConf.raise_()
        self.frameBaseConfBtn.raise_()
        self.frame.raise_()
        self.verticalLayout.addWidget(self.gBoxBaseConf)
        self.gBoxHwOpt = QtWidgets.QGroupBox(self.frameHwConf)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gBoxHwOpt.sizePolicy().hasHeightForWidth())
        self.gBoxHwOpt.setSizePolicy(sizePolicy)
        self.gBoxHwOpt.setAlignment(QtCore.Qt.AlignCenter)
        self.gBoxHwOpt.setObjectName("gBoxHwOpt")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gBoxHwOpt)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.txBWScale = QtWidgets.QLineEdit(self.gBoxHwOpt)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txBWScale.sizePolicy().hasHeightForWidth())
        self.txBWScale.setSizePolicy(sizePolicy)
        self.txBWScale.setMaximumSize(QtCore.QSize(30, 15))
        self.txBWScale.setAlignment(QtCore.Qt.AlignCenter)
        self.txBWScale.setObjectName("txBWScale")
        self.gridLayout_2.addWidget(self.txBWScale, 3, 4, 1, 1)
        self.txtL2BcastCluster = QtWidgets.QLineEdit(self.gBoxHwOpt)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtL2BcastCluster.sizePolicy().hasHeightForWidth())
        self.txtL2BcastCluster.setSizePolicy(sizePolicy)
        self.txtL2BcastCluster.setMaximumSize(QtCore.QSize(30, 15))
        self.txtL2BcastCluster.setAlignment(QtCore.Qt.AlignCenter)
        self.txtL2BcastCluster.setObjectName("txtL2BcastCluster")
        self.gridLayout_2.addWidget(self.txtL2BcastCluster, 0, 4, 1, 1)
        spacerItem11 = QtWidgets.QSpacerItem(0, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem11, 0, 12, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.gBoxHwOpt)
        self.label_20.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_20.setObjectName("label_20")
        self.gridLayout_2.addWidget(self.label_20, 3, 3, 1, 1)
        self.txCacheScale = QtWidgets.QLineEdit(self.gBoxHwOpt)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txCacheScale.sizePolicy().hasHeightForWidth())
        self.txCacheScale.setSizePolicy(sizePolicy)
        self.txCacheScale.setMaximumSize(QtCore.QSize(30, 15))
        self.txCacheScale.setCursorPosition(1)
        self.txCacheScale.setAlignment(QtCore.Qt.AlignCenter)
        self.txCacheScale.setObjectName("txCacheScale")
        self.gridLayout_2.addWidget(self.txCacheScale, 2, 4, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.gBoxHwOpt)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_19.sizePolicy().hasHeightForWidth())
        self.label_19.setSizePolicy(sizePolicy)
        self.label_19.setMaximumSize(QtCore.QSize(104, 15))
        self.label_19.setObjectName("label_19")
        self.gridLayout_2.addWidget(self.label_19, 2, 3, 1, 1)
        self.chBoxL2Bcast = QtWidgets.QCheckBox(self.gBoxHwOpt)
        self.chBoxL2Bcast.setObjectName("chBoxL2Bcast")
        self.gridLayout_2.addWidget(self.chBoxL2Bcast, 0, 0, 1, 1)
        self.chBoxStackedMem = QtWidgets.QCheckBox(self.gBoxHwOpt)
        self.chBoxStackedMem.setObjectName("chBoxStackedMem")
        self.gridLayout_2.addWidget(self.chBoxStackedMem, 3, 0, 1, 1)
        self.chBoxXCu = QtWidgets.QCheckBox(self.gBoxHwOpt)
        self.chBoxXCu.setObjectName("chBoxXCu")
        self.gridLayout_2.addWidget(self.chBoxXCu, 2, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gBoxHwOpt)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMaximumSize(QtCore.QSize(78, 16777215))
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 0, 3, 1, 1)
        self.frame_2 = QtWidgets.QFrame(self.gBoxHwOpt)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setSpacing(3)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.gridLayout_2.addWidget(self.frame_2, 0, 1, 1, 1)
        self.chBoxGAtomics = QtWidgets.QCheckBox(self.gBoxHwOpt)
        self.chBoxGAtomics.setEnabled(True)
        self.chBoxGAtomics.setChecked(True)
        self.chBoxGAtomics.setObjectName("chBoxGAtomics")
        self.gridLayout_2.addWidget(self.chBoxGAtomics, 0, 11, 1, 1)
        self.chBoxL2Bcast.raise_()
        self.chBoxXCu.raise_()
        self.frame_2.raise_()
        self.chBoxStackedMem.raise_()
        self.label_3.raise_()
        self.txtL2BcastCluster.raise_()
        self.txCacheScale.raise_()
        self.label_19.raise_()
        self.label_20.raise_()
        self.txBWScale.raise_()
        self.chBoxGAtomics.raise_()
        self.verticalLayout.addWidget(self.gBoxHwOpt)
        self.verticalLayout_6.addWidget(self.frameHwConf)
        self.frameSpdlm = QtWidgets.QFrame(self.frameRight)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameSpdlm.sizePolicy().hasHeightForWidth())
        self.frameSpdlm.setSizePolicy(sizePolicy)
        self.frameSpdlm.setFrameShape(QtWidgets.QFrame.Panel)
        self.frameSpdlm.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameSpdlm.setObjectName("frameSpdlm")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frameSpdlm)
        self.gridLayout_3.setContentsMargins(3, 3, 3, 3)
        self.gridLayout_3.setHorizontalSpacing(3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.frameRun = QtWidgets.QFrame(self.frameSpdlm)
        self.frameRun.setFrameShape(QtWidgets.QFrame.Panel)
        self.frameRun.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frameRun.setObjectName("frameRun")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frameRun)
        self.verticalLayout_5.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_5.setSpacing(2)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.btnRun = QtWidgets.QPushButton(self.frameRun)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnRun.sizePolicy().hasHeightForWidth())
        self.btnRun.setSizePolicy(sizePolicy)
        self.btnRun.setFlat(False)
        self.btnRun.setObjectName("btnRun")
        self.verticalLayout_5.addWidget(self.btnRun)
        self.gridLayout_3.addWidget(self.frameRun, 3, 2, 1, 1)
        self.frameSpdlmPresets = QtWidgets.QFrame(self.frameSpdlm)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameSpdlmPresets.sizePolicy().hasHeightForWidth())
        self.frameSpdlmPresets.setSizePolicy(sizePolicy)
        self.frameSpdlmPresets.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frameSpdlmPresets.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameSpdlmPresets.setObjectName("frameSpdlmPresets")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.frameSpdlmPresets)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.cBoxPresets = QtWidgets.QComboBox(self.frameSpdlmPresets)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cBoxPresets.sizePolicy().hasHeightForWidth())
        self.cBoxPresets.setSizePolicy(sizePolicy)
        self.cBoxPresets.setObjectName("cBoxPresets")
        self.cBoxPresets.addItem("")
        self.verticalLayout_10.addWidget(self.cBoxPresets)
        self.frameBtns = QtWidgets.QFrame(self.frameSpdlmPresets)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frameBtns.sizePolicy().hasHeightForWidth())
        self.frameBtns.setSizePolicy(sizePolicy)
        self.frameBtns.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frameBtns.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameBtns.setObjectName("frameBtns")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frameBtns)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(3)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.btnSavePreset = QtWidgets.QToolButton(self.frameBtns)
        self.btnSavePreset.setObjectName("btnSavePreset")
        self.horizontalLayout_7.addWidget(self.btnSavePreset)
        self.btnSaveAsPreset = QtWidgets.QToolButton(self.frameBtns)
        self.btnSaveAsPreset.setObjectName("btnSaveAsPreset")
        self.horizontalLayout_7.addWidget(self.btnSaveAsPreset)
        self.btnDelPreset = QtWidgets.QToolButton(self.frameBtns)
        self.btnDelPreset.setObjectName("btnDelPreset")
        self.horizontalLayout_7.addWidget(self.btnDelPreset)
        self.verticalLayout_10.addWidget(self.frameBtns)
        self.gridLayout_3.addWidget(self.frameSpdlmPresets, 3, 1, 1, 1)
        self.frameTitle_2 = QtWidgets.QFrame(self.frameSpdlm)
        self.frameTitle_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frameTitle_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frameTitle_2.setObjectName("frameTitle_2")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frameTitle_2)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.line_5 = QtWidgets.QFrame(self.frameTitle_2)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.horizontalLayout_6.addWidget(self.line_5)
        self.lblRun = QtWidgets.QLabel(self.frameTitle_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblRun.sizePolicy().hasHeightForWidth())
        self.lblRun.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.lblRun.setFont(font)
        self.lblRun.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblRun.setObjectName("lblRun")
        self.horizontalLayout_6.addWidget(self.lblRun)
        self.line_2 = QtWidgets.QFrame(self.frameTitle_2)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout_6.addWidget(self.line_2)
        self.gridLayout_3.addWidget(self.frameTitle_2, 0, 1, 1, 2)
        self.framePath = QtWidgets.QFrame(self.frameSpdlm)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.framePath.sizePolicy().hasHeightForWidth())
        self.framePath.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.framePath.setFont(font)
        self.framePath.setFrameShape(QtWidgets.QFrame.Panel)
        self.framePath.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.framePath.setObjectName("framePath")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.framePath)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setSpacing(0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.txtPath = QtWidgets.QLineEdit(self.framePath)
        self.txtPath.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtPath.sizePolicy().hasHeightForWidth())
        self.txtPath.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.txtPath.setFont(font)
        self.txtPath.setInputMask("")
        self.txtPath.setText("")
        self.txtPath.setFrame(False)
        self.txtPath.setAlignment(QtCore.Qt.AlignJustify|QtCore.Qt.AlignVCenter)
        self.txtPath.setObjectName("txtPath")
        self.horizontalLayout_10.addWidget(self.txtPath)
        self.btnBrowse = QtWidgets.QToolButton(self.framePath)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        self.btnBrowse.setFont(font)
        self.btnBrowse.setPopupMode(QtWidgets.QToolButton.InstantPopup)
        self.btnBrowse.setAutoRaise(True)
        self.btnBrowse.setArrowType(QtCore.Qt.NoArrow)
        self.btnBrowse.setObjectName("btnBrowse")
        self.horizontalLayout_10.addWidget(self.btnBrowse)
        self.txtPostfix = QtWidgets.QLineEdit(self.framePath)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtPostfix.sizePolicy().hasHeightForWidth())
        self.txtPostfix.setSizePolicy(sizePolicy)
        self.txtPostfix.setMaximumSize(QtCore.QSize(100, 16777215))
        self.txtPostfix.setFrame(False)
        self.txtPostfix.setObjectName("txtPostfix")
        self.horizontalLayout_10.addWidget(self.txtPostfix)
        self.gridLayout_3.addWidget(self.framePath, 1, 1, 1, 2)
        self.verticalLayout_6.addWidget(self.frameSpdlm)
        self.horizontalLayout.addWidget(self.splitter)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.wgtExtOpt.setCurrentIndex(0)
        self.wgtExtOpt_row2.setCurrentIndex(0)
        self.wgtExtOpt_row3.setCurrentIndex(0)
        self.cBoxConfs.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MIMS"))
        self.lblDnnConf.setText(_translate("MainWindow", "DNN Config"))
        self.gBoxSWOpt.setTitle(_translate("MainWindow", "SW Options"))
        self.cBoxModels.setItemText(0, _translate("MainWindow", "[ onnx model ]"))
        self.btnRL.setText(_translate("MainWindow", "RL"))
        self.chBoxMGPU.setToolTip(_translate("MainWindow", "<html><head/><body><p>Enable Multiple GPUs.</p></body></html>"))
        self.btnMGPU.setToolTip(_translate("MainWindow", "<html><head/><body><p>Enable Multiple GPUs.</p></body></html>"))
        self.btnMGPU.setText(_translate("MainWindow", "MGPU"))
        self.btnGeneral.setText(_translate("MainWindow", "General"))
        self.chBoxTraining.setToolTip(_translate("MainWindow", "<html><head/><body><p>Keyword: Training</p><p>When Disabled, MIMS evaluates only forward pass.</p></body></html>"))
        self.chBoxTraining.setText(_translate("MainWindow", "Training"))
        self.chBoxFusion.setToolTip(_translate("MainWindow", "<html><head/><body><p>Keyword: KernelFusion</p><p>When enabled, the some layers are fused to the previous layers.</p><p>Partial fusion is not implemented in MIMS.</p></body></html>"))
        self.chBoxFusion.setText(_translate("MainWindow", "KernelFusion"))
        self.label_2.setToolTip(_translate("MainWindow", "<html><head/><body><p>Keyword: DataFormat</p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "DataFormat "))
        self.cBoxDataFormat.setToolTip(_translate("MainWindow", "<html><head/><body><p>Keyword: DataFormat</p><p>BF16 is applicable for MI100 only.</p></body></html>"))
        self.cBoxDataFormat.setItemText(0, _translate("MainWindow", "FP16"))
        self.cBoxDataFormat.setItemText(1, _translate("MainWindow", "BF16"))
        self.cBoxDataFormat.setItemText(2, _translate("MainWindow", "FP32"))
        self.cBoxDataFormat.setItemText(3, _translate("MainWindow", "FP64"))
        self.cBoxDataFormat.setItemText(4, _translate("MainWindow", "INT8"))
        self.label.setToolTip(_translate("MainWindow", "<html><head/><body><p>Keyword: BatchSize</p></body></html>"))
        self.label.setText(_translate("MainWindow", "BatchSize"))
        self.txtBatchSize.setToolTip(_translate("MainWindow", "<html><head/><body><p>Keyword: BatchSize</p></body></html>"))
        self.txtBatchSize.setText(_translate("MainWindow", "32"))
        self.chBoxOptimizeGraph.setToolTip(_translate("MainWindow", "<html><head/><body><p>Keyword: OptimizeGraph</p><p>The graphs are ALWAYS otimized in MIMS :)</p><p>Irrespective of this option being enabled/disabled</p></body></html>"))
        self.chBoxOptimizeGraph.setText(_translate("MainWindow", "OptimizeGraph"))
        self.chBoxCalibrated.setToolTip(_translate("MainWindow", "<html><head/><body><p>Keyword: Calibrated</p></body></html>"))
        self.chBoxCalibrated.setText(_translate("MainWindow", "Calibrated"))
        self.chBoxABinLDS.setToolTip(_translate("MainWindow", "<html><head/><body><p>Keyword: ABinLDS</p><p>Pre-requesite -&gt; TOTAL_VGPR_SIZE_PER_CU = 0 (in HW Config)</p><p>If TOTAL_VGPR_SIZE_PER_CU == 0 then</p><p>----If A+B in LDS only enabled then</p><p>--------A and B inputs are in LDS only (Typically used for Vega20)</p><p>----else</p><p>--------A (and o/p C) stored in VGPRs and B in LDS</p><p>else</p><p>----A in arch VGPRs, B in LDS and C in accum VGPRs</p></body></html>"))
        self.chBoxABinLDS.setText(_translate("MainWindow", "ABinLDS"))
        self.label_6.setText(_translate("MainWindow", "Tmax"))
        self.txtTmax.setText(_translate("MainWindow", "5"))
        self.label_5.setText(_translate("MainWindow", "CPUThreads"))
        self.txtCpuThreads.setText(_translate("MainWindow", "32"))
        self.label_4.setText(_translate("MainWindow", "GPUCount"))
        self.txtGPUCount.setText(_translate("MainWindow", "8"))
        self.label_7.setText(_translate("MainWindow", "XGMILinksPerGPU"))
        self.txtXGMILinksPerGPU.setText(_translate("MainWindow", "6"))
        self.label_11.setText(_translate("MainWindow", "XGMI_BW"))
        self.txtXGMI_BW.setToolTip(_translate("MainWindow", "GBps"))
        self.txtXGMI_BW.setText(_translate("MainWindow", "64"))
        self.label_12.setText(_translate("MainWindow", "XGMI_BWEfficiency"))
        self.txtXGMI_BWEfficiency.setText(_translate("MainWindow", "0.8"))
        self.label_13.setText(_translate("MainWindow", "NumGradientBits"))
        self.txtNumGradientBits.setText(_translate("MainWindow", "16"))
        self.label_10.setText(_translate("MainWindow", "StartupLatency"))
        self.txtStartupLatency.setToolTip(_translate("MainWindow", "microseconds"))
        self.txtStartupLatency.setText(_translate("MainWindow", "3"))
        self.chBoxWeakScaling.setText(_translate("MainWindow", "WeakScaling"))
        self.chBoxDisableL2Opti.setToolTip(_translate("MainWindow", "<html><head/><body><p>Keyword: DisableL2Opti</p><p>Disable MIMS assumption of &quot;reverse&quot; traversal&quot; on alternating Layers to optimize L2 utilization.</p><p>If enabled, MIMS assumes L2 hit-rate of 0 if activation_size &gt; L2 cache size.</p></body></html>"))
        self.chBoxDisableL2Opti.setText(_translate("MainWindow", "DisableL2Opti"))
        self.chBoxDisableTrailKRepart.setToolTip(_translate("MainWindow", "<html><head/><body><p>Keyword: DisableTrailKRepart</p><p>Disables Trail Kernel K partition. Forces splitK=1.</p></body></html>"))
        self.chBoxDisableTrailKRepart.setText(_translate("MainWindow", "DisableTrailKRepart"))
        self.chBoxDisableMainKPart.setToolTip(_translate("MainWindow", "<html><head/><body><p>Keyword: DisableMainKPart</p><p>Disables Main Kernel K partition. Forces splitK=1</p></body></html>"))
        self.chBoxDisableMainKPart.setText(_translate("MainWindow", "DisableMainKPart"))
        self.chBoxDisableTrailOpti.setToolTip(_translate("MainWindow", "<html><head/><body><p>Keyword: DisableTrailOpti</p><p>Forces Trail Kernel splitK to be the same as Main Kernel SplitK.</p></body></html>"))
        self.chBoxDisableTrailOpti.setText(_translate("MainWindow", "DisableTrailOpti"))
        self.label_18.setToolTip(_translate("MainWindow", "<html><head/><body><p>Keyword: PerfThreshold</p></body></html>"))
        self.label_18.setText(_translate("MainWindow", "  PerfThreshold"))
        self.txtPerfThreshold.setToolTip(_translate("MainWindow", "<html><head/><body><p>Keyword: PerfThreshold</p><p>MIMS can choose the second best solution if the #CUs is greater than the best solution and the #cycles best - secondbest &lt; threshold%.</p><p>If set to 0, MIMS chooses the best performing configuration.</p></body></html>"))
        self.txtPerfThreshold.setText(_translate("MainWindow", "0"))
        self.chBoxTileGranularity.setToolTip(_translate("MainWindow", "<html><head/><body><p>Keyword: TileGranularity</p><p>Requires noTrail enabled.</p><p>If enabled </p><p>MIMS evaluates performance based on TileAwareSolutionSelection method by evaluating Tile and CU granularity for edge cases.</p><p>Else</p><p>MIMS discards all solutions that generates edge cases. User needs to be careful with this option as it may result in MIMS finding &quot;No Solution&quot; for certain layers.</p></body></html>"))
        self.chBoxTileGranularity.setText(_translate("MainWindow", "TileGranularity"))
        self.label_8.setToolTip(_translate("MainWindow", "All-Reduce Algorithm"))
        self.label_8.setText(_translate("MainWindow", "Algorithm"))
        self.cBoxAlgorithm.setToolTip(_translate("MainWindow", "All-Reduce Algorithm"))
        self.cBoxAlgorithm.setItemText(0, _translate("MainWindow", "CR8G"))
        self.cBoxAlgorithm.setItemText(1, _translate("MainWindow", "Ring"))
        self.cBoxAlgorithm.setItemText(2, _translate("MainWindow", "RHDD"))
        self.cBoxAlgorithm.setItemText(3, _translate("MainWindow", "H. Reduce"))
        self.label_9.setText(_translate("MainWindow", "Topology"))
        self.cBoxTopology.setToolTip(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Multi-GPU Topology</span></p><p>CR (Chordal Ring)</p><p>FC (Fully Connected)</p><p>HMC (Hybrid Mesh Cube)</p><p>HQ (Hierarchical Quad)</p><p>X8 (X8)</p></body></html>"))
        self.cBoxTopology.setItemText(0, _translate("MainWindow", "CR"))
        self.cBoxTopology.setItemText(1, _translate("MainWindow", "FC"))
        self.cBoxTopology.setItemText(2, _translate("MainWindow", "HMC"))
        self.cBoxTopology.setItemText(3, _translate("MainWindow", "X8"))
        self.cBoxTopology.setItemText(4, _translate("MainWindow", "HQ"))
        self.label_14.setText(_translate("MainWindow", "MultiNode"))
        self.txtMultiNode.setText(_translate("MainWindow", "1"))
        self.label_15.setText(_translate("MainWindow", "MultiNodeBW"))
        self.txtMultiNodeBW.setToolTip(_translate("MainWindow", "GBps"))
        self.txtMultiNodeBW.setText(_translate("MainWindow", "10"))
        self.label_16.setText(_translate("MainWindow", "MultiNodeLinks"))
        self.txtMultiNodeLinks.setText(_translate("MainWindow", "1"))
        self.label_17.setText(_translate("MainWindow", "MNStartupLatency"))
        self.txtMNStartupLatency.setToolTip(_translate("MainWindow", "microseconds"))
        self.txtMNStartupLatency.setText(_translate("MainWindow", "16"))
        self.chBoxSDMA_Xfer.setText(_translate("MainWindow", "SDMA_Xfer"))
        self.chBoxUserDefMT.setToolTip(_translate("MainWindow", "<html><head/><body><p>Keyword: UserDefMT</p><p>Enable User Defined Tile Size definition.</p><p>MIMS will bypass its optimization process and explore for best solutions based on tile definitions defined by the user.</p></body></html>"))
        self.chBoxUserDefMT.setText(_translate("MainWindow", "UserDefMT"))
        self.label_21.setToolTip(_translate("MainWindow", "<html><head/><body><p>Keyword: MainMT0</p><p>Main Kernel - Tile Dimension 0 (MT0)</p><p>Requires UserDefMT enabled.</p><p>Main Kernel MT1 should also be defined.</p><p>If UserDefMT enabled and Main Kernel MT0 and Main Kernel MT1 set to 0, MIMS chooses the tile sizes for Main Kernel.</p></body></html>"))
        self.label_21.setText(_translate("MainWindow", "MainMT0"))
        self.txtMainMT0.setToolTip(_translate("MainWindow", "<html><head/><body><p>Keyword: mainMT0</p><p>Main Kernel - Tile Dimension 0 (MT0)</p><p>Requires UserDefMT enabled.</p><p>Main Kernel MT1 should also be defined.</p><p>If UserDefMT enabled and Main Kernel MT0 and Main Kernel MT1 set to 0, MIMS chooses the tile sizes for Main Kernel.</p></body></html>"))
        self.txtMainMT0.setAccessibleDescription(_translate("MainWindow", "Main Kernel - Tile dimension 0 (MT0)"))
        self.txtMainMT0.setText(_translate("MainWindow", "16"))
        self.label_22.setToolTip(_translate("MainWindow", "<html><head/><body><p>Keyword: MainMT1</p><p>Main Kernel - Tile Dimension 1 (MT1). </p><p>Requires UserDefMT enabled.</p><p>Main Kernel MT0 should also be defined.</p><p>If UserDefMT enabled and Main Kernel MT0 and Main Kernel MT1 set to 0, MIMS chooses the tile sizes for Main Kernel.</p></body></html>"))
        self.label_22.setText(_translate("MainWindow", "MainMT1"))
        self.txtMainMT1.setToolTip(_translate("MainWindow", "<html><head/><body><p>Keyword: MainMT1</p><p>Main Kernel - Tile Dimension 1 (MT1). </p><p>Requires UserDefMT enabled.</p><p>Main Kernel MT0 should also be defined.</p><p>If UserDefMT enabled and Main Kernel MT0 and Main Kernel MT1 set to 0, MIMS chooses the tile sizes for Main Kernel.</p></body></html>"))
        self.txtMainMT1.setAccessibleDescription(_translate("MainWindow", "Main Kernel - Tile Dimension 1 (MT1)"))
        self.txtMainMT1.setText(_translate("MainWindow", "16"))
        self.chBoxNoTrail.setToolTip(_translate("MainWindow", "<html><head/><body><p>Keyword: NoTrail</p><p>Disables Trail Kernel completely.</p><p>MIMS will search for best solution with only Main Kernel.</p></body></html>"))
        self.chBoxNoTrail.setText(_translate("MainWindow", "NoTrail"))
        self.label_23.setToolTip(_translate("MainWindow", "<html><head/><body><p>Keyword: TrailMT0</p><p>Trail Kernel - Tile Dimension 0 (MT0)</p><p>Requires noTrail disabled. </p><p>Requires UserDefMT enabled. </p><p>Trail Kernel MT1 should also be defined. </p><p>If UserDefMT enabled and Trail Kernel MT0 and Trail Kernel MT1 set to 0, MIMS chooses the tile sizes for Trail Kernel.</p><p><br/></p></body></html>"))
        self.label_23.setText(_translate("MainWindow", "TrailMT0"))
        self.txtTrailMT0.setToolTip(_translate("MainWindow", "<html><head/><body><p>Keyword: TrailMT0</p><p>Trail Kernel - Tile Dimension 0 (MT0)</p><p>Requires noTrail disabled. </p><p>Requires UserDefMT enabled. </p><p>Trail Kernel MT1 should also be defined. </p><p>If UserDefMT enabled and Trail Kernel MT0 and Trail Kernel MT1 set to 0, MIMS chooses the tile sizes for Trail Kernel.</p><p><br/></p></body></html>"))
        self.txtTrailMT0.setAccessibleDescription(_translate("MainWindow", " Trail Kernel - Tile dimension 0 (MT0)"))
        self.txtTrailMT0.setText(_translate("MainWindow", "16"))
        self.label_24.setToolTip(_translate("MainWindow", "<html><head/><body><p>Keyword: TrailMT1</p><p>Trail Kernel - Tile Dimension 1 (MT1)</p><p>Requires noTrail disabled. </p><p>Requires UserDefMT enabled. </p><p>Trail Kernel MT0 should also be defined. </p><p>If UserDefMT enabled and Trail Kernel MT0 and Trail Kernel MT1 set to 0, MIMS chooses the tile sizes for Trail Kernel.</p></body></html>"))
        self.label_24.setText(_translate("MainWindow", "TrailMT1"))
        self.txtTrailMT1.setToolTip(_translate("MainWindow", "<html><head/><body><p>Keyword: TrailMT1</p><p>Trail Kernel - Tile Dimension 1 (MT1)</p><p>Requires noTrail disabled. </p><p>Requires UserDefMT enabled. </p><p>Trail Kernel MT0 should also be defined. </p><p>If UserDefMT enabled and Trail Kernel MT0 and Trail Kernel MT1 set to 0, MIMS chooses the tile sizes for Trail Kernel.</p></body></html>"))
        self.txtTrailMT1.setAccessibleDescription(_translate("MainWindow", " Trail Kernel - Tile dimension 1 (MT1)"))
        self.txtTrailMT1.setText(_translate("MainWindow", "16"))
        self.gBoxPreviewModel.setTitle(_translate("MainWindow", "Preview"))
        self.lblHwConf.setText(_translate("MainWindow", "HW Config"))
        self.gBoxBaseConf.setTitle(_translate("MainWindow", "Base Config"))
        self.cBoxConfs.setItemText(0, _translate("MainWindow", "[ base config ]"))
        self.btnNewConf.setToolTip(_translate("MainWindow", "New"))
        self.btnNewConf.setText(_translate("MainWindow", "New"))
        self.btnSaveConf.setToolTip(_translate("MainWindow", "Save"))
        self.btnSaveConf.setText(_translate("MainWindow", "Save"))
        self.btnSaveAsConf.setToolTip(_translate("MainWindow", "Save As"))
        self.btnSaveAsConf.setText(_translate("MainWindow", "Save As"))
        self.btnDelConf.setToolTip(_translate("MainWindow", "Delete"))
        self.btnDelConf.setText(_translate("MainWindow", "Delete"))
        self.btnAddRow.setToolTip(_translate("MainWindow", "Add Row"))
        self.btnAddRow.setText(_translate("MainWindow", "+"))
        self.btnRemRow.setToolTip(_translate("MainWindow", "Remove Row"))
        self.btnRemRow.setText(_translate("MainWindow", "-"))
        self.gBoxHwOpt.setTitle(_translate("MainWindow", "HW Options"))
        self.txBWScale.setToolTip(_translate("MainWindow", "<html><head/><body><p>Keyword: BWScale</p><p>Values range from 0 - 1.</p><p>Scale BW utilization.</p><p>Currently assumes full BW utilization (TBD).</p></body></html>"))
        self.txBWScale.setText(_translate("MainWindow", "1"))
        self.txtL2BcastCluster.setToolTip(_translate("MainWindow", "<html><head/><body><p>Keyword: L2BCastCluster</p></body></html>"))
        self.txtL2BcastCluster.setText(_translate("MainWindow", "4"))
        self.label_20.setToolTip(_translate("MainWindow", "<html><head/><body><p>Keyword: BWScale</p></body></html>"))
        self.label_20.setAccessibleDescription(_translate("MainWindow", "Fudge factor for BW (less than 1). 1 implies full BW utilization."))
        self.label_20.setText(_translate("MainWindow", "Scale BW"))
        self.txCacheScale.setToolTip(_translate("MainWindow", "<html><head/><body><p>Keyword: CacheScale</p><p>Values range from 0 - 1.</p><p>Scale L2 and L3 cache available.</p><p>Default value set to 0.8 based on emperical data.</p></body></html>"))
        self.txCacheScale.setText(_translate("MainWindow", "0.8"))
        self.label_19.setToolTip(_translate("MainWindow", "<html><head/><body><p>Keyword: CacheScale</p></body></html>"))
        self.label_19.setText(_translate("MainWindow", "Scale Cache Size <=1"))
        self.chBoxL2Bcast.setToolTip(_translate("MainWindow", "<html><head/><body><p>Keyword: L2Bcast</p></body></html>"))
        self.chBoxL2Bcast.setText(_translate("MainWindow", "L2 Broadcast"))
        self.chBoxStackedMem.setToolTip(_translate("MainWindow", "<html><head/><body><p>Keyword: StackedMem</p></body></html>"))
        self.chBoxStackedMem.setText(_translate("MainWindow", "Stacked Mem"))
        self.chBoxXCu.setToolTip(_translate("MainWindow", "<html><head/><body><p>Keyword: XCu</p></body></html>"))
        self.chBoxXCu.setText(_translate("MainWindow", "Cross-CU Comm"))
        self.label_3.setToolTip(_translate("MainWindow", "<html><head/><body><p>Keyword: L2BCastCluster</p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "L2 Bcast Cluster"))
        self.chBoxGAtomics.setToolTip(_translate("MainWindow", "<html><head/><body><p>Keyword: GAtomics</p><p>If enabled (Default), allows atomic updates.</p><p>If disabled, MIMS assumes software defined atomic updates based on compare-and-swap. TBD - Define faliure rate for compare-and-swap. </p></body></html>"))
        self.chBoxGAtomics.setText(_translate("MainWindow", "Atomic"))
        self.btnRun.setText(_translate("MainWindow", "MIMS"))
        self.cBoxPresets.setItemText(0, _translate("MainWindow", "[ preset ]"))
        self.btnSavePreset.setToolTip(_translate("MainWindow", "Save"))
        self.btnSavePreset.setText(_translate("MainWindow", "Save"))
        self.btnSaveAsPreset.setToolTip(_translate("MainWindow", "Save As"))
        self.btnSaveAsPreset.setText(_translate("MainWindow", "Save As"))
        self.btnDelPreset.setToolTip(_translate("MainWindow", "Delete"))
        self.btnDelPreset.setText(_translate("MainWindow", "Delete"))
        self.lblRun.setText(_translate("MainWindow", "Run"))
        self.txtPath.setPlaceholderText(_translate("MainWindow", "Output Path"))
        self.btnBrowse.setText(_translate("MainWindow", "..."))
        self.txtPostfix.setPlaceholderText(_translate("MainWindow", "File Postfix"))


